### ISSUE TITLE
superglowglass lighting bug

### ISSUE THREAD

**Issue by RHRhino** [davisonio/craig-server_game#76]
I recognized that superglowglass is causing the lighting [bug ](https://github.com/minetest/minetest/issues/3964)I reported earlier. This bug can be reproduced by placing superglowglass above a full block and removing the block. The new light does not disappear even if you remove the superglowglas. So far it happens only with superglowglass not with torches.

1) before placing
![screenshot_20160910_161015](https://cloud.githubusercontent.com/assets/6941454/18411171/b3af328e-7772-11e6-93e4-dfdabc58ea7a.png)
2) superglowglass placed above a full node
![screenshot_20160910_161034](https://cloud.githubusercontent.com/assets/6941454/18411174/b3b4d522-7772-11e6-80db-8318d541b01d.png)
3) removing the block causes the new light
![screenshot_20160910_161049](https://cloud.githubusercontent.com/assets/6941454/18411173/b3b380e6-7772-11e6-943e-df5ad8cc1305.png)
4) the light does not disappear even without the superglowglass
![screenshot_20160910_161101](https://cloud.githubusercontent.com/assets/6941454/18411172/b3b16b12-7772-11e6-8fd7-8f2884dd8a7b.png)

**Comment by davisonio** [comment]
Thanks for reporting @RHRhino I'll take a look at this

**Comment by davisonio** [comment]
Ok I think I might have found the problem.

Super glow glass uses `light_source = 15` ([link](https://github.com/davisonio/craig-server_game/blob/master/mods/moreblocks/nodes.lua#L287)) when the maximum recommended in the [minetest docs](http://dev.minetest.net/minetest.register_node) is `14`. 

To fix this we need to change moreblocks so that it only uses a light source of up to 14. Also ideally, in Minetest Core there should be no way to cause this problem.

**Comment by RHRhino** [comment]
hey @davisonio did you already updated the server? Because the bug is still there.

**Comment by davisonio** [comment]
Hey, just updated the game + server so this should be fixed :)
